# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, feature/github_workflow ]
  #pull_request:
  #  branches: [ master, feature/github_workflow ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

      
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  styleguide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
      
      
      
  docker:
    runs-on: ubuntu-latest
   #needs: [styleguide]
    steps:
      - uses: actions/checkout@v2
        
      - name: docker_build
        run: |
          docker build -t test98767767/test_app:version_1 .
      
      - name: docker_push
        run: |
          docker login --username=test98767767 --password=test98767767
          docker push test98767767/test_app:version_1
        # Yes, this is my login and pass
          
      - name: docker_run
        run: |
          docker run -d test98767767/test_app:version_1
          
  deploy:
    needs: [docker]
    runs-on: [self-hosted]
    steps:
     # - name: Set tag to env
     #   run: echo ::set-env name=TAG::$(echo ${GITHUB_REF:11})
      - name: Send webhook for deploy
        run: |
          remove-item alias:curl
          curl --silent --show-error --fail -X POST 192.168.10.125:5000 -H 'Content-Type: application/json' -d '{test98767767/test_app:version_1 test_app}'

